-- ============================================
-- DESACTIVAR RLS EN TODAS LAS TABLAS
-- ============================================

ALTER TABLE teachers DISABLE ROW LEVEL SECURITY;
ALTER TABLE groups DISABLE ROW LEVEL SECURITY;
ALTER TABLE students DISABLE ROW LEVEL SECURITY;
ALTER TABLE subjects DISABLE ROW LEVEL SECURITY;
ALTER TABLE programaciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE situaciones_aprendizaje DISABLE ROW LEVEL SECURITY;
ALTER TABLE units DISABLE ROW LEVEL SECURITY;
ALTER TABLE instruments DISABLE ROW LEVEL SECURITY;
ALTER TABLE grades DISABLE ROW LEVEL SECURITY;
ALTER TABLE attendance DISABLE ROW LEVEL SECURITY;
ALTER TABLE observations DISABLE ROW LEVEL SECURITY;
ALTER TABLE measures DISABLE ROW LEVEL SECURITY;
ALTER TABLE recoveries DISABLE ROW LEVEL SECURITY;

-- Verificar que se desactivó correctamente
SELECT '✅ RLS desactivado en todas las tablas' AS mensaje;
